name: Build Typst documents
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Compile Typst documents
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            fr.typ
            en.typ

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: PDFs
          path: "*.pdf"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v3.0.0
        with:
          tag_name: build-${{ github.sha }}
          name: "Build ${{ env.DATE }}"
          files: "*.pdf"
